-- T03: additive only. Apply through the operator's authorized migration procedure.
ALTER TABLE whiteboard_sessions ADD COLUMN IF NOT EXISTS state_revision bigint NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS whiteboard_object_ownership (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    board_id bigint NOT NULL REFERENCES whiteboard_sessions(id),
    object_kind varchar(10) NOT NULL,
    object_id varchar(100) NOT NULL,
    owner_user_id bigint REFERENCES user_accounts(id),
    deleted boolean NOT NULL,
    CONSTRAINT uk_whiteboard_object UNIQUE (board_id, object_kind, object_id)
);
-- Historical objects are imported lazily under the board lock with owner_user_id NULL.
-- Deleted identities are retained. Do not truncate this table while boards/history exist.
