package com.morales.chemicallab.security;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.morales.chemicallab.ChemicalLabBackendApplication;
import com.morales.chemicallab.config.SessionCleanup;
import com.morales.chemicallab.dto.LoginRequest;
import com.morales.chemicallab.entity.*;
import com.morales.chemicallab.repository.*;
import com.morales.chemicallab.service.*;
import io.jsonwebtoken.Jwts;
import io.jsonwebtoken.security.Keys;
import org.junit.jupiter.api.*;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.CsvSource;
import org.springframework.boot.SpringApplication;
import org.springframework.context.ConfigurableApplicationContext;
import org.springframework.core.env.StandardEnvironment;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.messaging.simp.stomp.*;
import org.springframework.messaging.support.*;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.support.TransactionTemplate;
import org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping;

import java.net.URI;
import java.net.http.*;
import java.security.SecureRandom;
import java.sql.Connection;
import java.sql.DriverManager;
import java.time.*;
import java.util.*;
import java.util.concurrent.*;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.function.Consumer;

import static org.assertj.core.api.Assertions.*;

/** Real HTTP, JPA and PostgreSQL. Never points at an existing school database. */
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
class AccountSessionsDbTest {
    private static final String PASSWORD = "FictitiousPass123";
    private final AtomicInteger sequence = new AtomicInteger();
    private final ObjectMapper json = new ObjectMapper();
    private final HttpClient http = HttpClient.newHttpClient();
    private final byte[] key = new byte[32];
    private ConfigurableApplicationContext app;
    private String schema;
    private String origin;
    private Connection control;

    @BeforeAll void startDatabaseSchema() throws Exception {
        String url = setting("spring.datasource.url");
        if (!url.matches("jdbc:postgresql://127\\.0\\.0\\.1:[0-9]+/chemicallab_t01_test")) {
            throw new IllegalStateException("Only disposable loopback PostgreSQL chemicallab_t01_test is allowed");
        }
        new SecureRandom().nextBytes(key);
        schema = "t02_" + UUID.randomUUID().toString().replace("-", "");
        control = DriverManager.getConnection(url, setting("spring.datasource.username"), setting("spring.datasource.password"));
        try (var sql = control.createStatement()) {
            sql.execute("CREATE SCHEMA " + schema);
            // Existing pre-T02 table: exercise the additive upgrade, with a preserved account.
            sql.execute("CREATE TABLE " + schema + ".user_accounts (id bigint generated by default as identity primary key, "
                    + "username varchar(255) unique not null, email varchar(255) unique, password varchar(255) not null, "
                    + "role varchar(255) not null, active boolean not null, temporary_password boolean not null, "
                    + "created_at timestamp, updated_at timestamp)");
            sql.execute("INSERT INTO " + schema + ".user_accounts(username,password,role,active,temporary_password) "
                    + "VALUES ('preservedfixture','fictitious-hash','ADMINISTRADOR',true,false)");
        }
        startApp();
        assertThat(users().findByUsername("preservedfixture").orElseThrow().getCredentialsVersion()).isZero();
    }

    @AfterAll void cleanup() throws Exception {
        SecurityContextHolder.clearContext();
        if (app != null) app.close();
        if (control != null) {
            try (var statement = control.createStatement()) { statement.execute("DROP SCHEMA " + schema + " CASCADE"); }
            control.close();
        }
    }

    private void startApp() {
        var environment = new StandardEnvironment();
        environment.getPropertySources().remove(StandardEnvironment.SYSTEM_ENVIRONMENT_PROPERTY_SOURCE_NAME);
        environment.getPropertySources().remove(StandardEnvironment.SYSTEM_PROPERTIES_PROPERTY_SOURCE_NAME);
        var application = new SpringApplication(ChemicalLabBackendApplication.class);
        application.setEnvironment(environment);
        app = application.run("--spring.profiles.active=test", "--spring.config.location=classpath:/",
                "--server.address=127.0.0.1", "--server.port=0",
                "--spring.datasource.url=" + setting("spring.datasource.url") + "?currentSchema=" + schema,
                "--spring.datasource.username=" + setting("spring.datasource.username"),
                "--spring.datasource.password=" + setting("spring.datasource.password"),
                "--spring.jpa.properties.hibernate.default_schema=" + schema,
                "--spring.jpa.hibernate.ddl-auto=update",
                "--app.jwt.secret=" + Base64.getEncoder().encodeToString(key),
                "--app.demo.enabled=false", "--app.bootstrap.admin.enabled=false",
                "--spring.main.banner-mode=off", "--logging.level.root=ERROR");
        origin = "http://127.0.0.1:" + app.getEnvironment().getProperty("local.server.port");
    }

    @Test void allRestMappingsRejectTemporaryAndInactiveAccountsForEveryRole() throws Exception {
        var mappings = app.getBean("requestMappingHandlerMapping", RequestMappingHandlerMapping.class).getHandlerMethods();
        var routes = new TreeSet<String>();
        mappings.keySet().forEach(mapping -> mapping.getPatternValues().forEach(path -> {
            if (path.startsWith("/api/") && !path.startsWith("/api/auth/") && !path.equals("/api/health")) {
                mapping.getMethodsCondition().getMethods().forEach(method ->
                        routes.add(method.name() + " " + path.replaceAll("\\{[^}]+}", "1")));
            }
        }));
        assertThat(routes.size()).isGreaterThanOrEqualTo(118);
        for (Role role : Role.values()) {
            for (boolean temporary : List.of(false, true)) {
                UserAccount account = account(role, temporary);
                String token = login(account);
                if (temporary) {
                    for (String route : routes) {
                        var parts = route.split(" ", 2);
                        var response = request(parts[0], parts[1], token, "{}");
                        assertThat(response.statusCode()).as(role + " temporary " + route).isEqualTo(403);
                        assertThat(response.body()).contains("PASSWORD_CHANGE_REQUIRED");
                    }
                    assertStatus("GET", "/api/auth/me", token, null, 200);
                    assertThat(body(request("GET", "/api/auth/me", token, null)).get("email").isNull()).isTrue();
                    for (String route : List.of("GET /api/auth/logout", "POST /api/auth/me", "GET /api/auth/new-route")) {
                        var parts = route.split(" ", 2);
                        assertStatus(parts[0], parts[1], token, "{}", 403);
                    }
                }
                mutate(account, user -> user.setActive(false));
                assertStatus("POST", "/api/auth/login", null, loginBody(account, PASSWORD), 401);
                for (String route : routes) {
                    var parts = route.split(" ", 2);
                    assertStatus(parts[0], parts[1], token, "{}", 401);
                }
                assertStatus("GET", "/api/auth/me", token, null, 401);
            }
        }
        System.out.println("T02 matrix: " + routes.size() + " business REST mappings; three roles; temporary and inactive states; real HTTP/PostgreSQL.");
    }

    @Test void legitimateRolesFilesSnapshotsAndOwnershipRemainEnforced() throws Exception {
        UserAccount admin = account(Role.ADMINISTRADOR, false);
        UserAccount teacher = account(Role.DOCENTE, false);
        UserAccount student = account(Role.ESTUDIANTE, false);
        TeacherProfile tp = app.getBean(TeacherProfileRepository.class).findByUser(teacher).orElseThrow();
        var concept = app.getBean(ConceptContentRepository.class).saveAndFlush(ConceptContent.builder()
                .title("Fictitious history").category("Chemistry").explanation("Preserved lesson")
                .createdByTeacher(tp).status(ConceptStatus.PUBLISHED).build());
        app.getBean(ConceptAssignmentRepository.class).saveAndFlush(ConceptAssignment.builder()
                .conceptContent(concept).teacher(tp).grade("3").section("A").build());
        byte[] bytes = new byte[]{1, 2, 3};
        var material = app.getBean(ConceptMaterialRepository.class).saveAndFlush(ConceptMaterial.builder()
                .conceptContent(concept).type(MaterialType.FILE).fileData(bytes).fileSize(3L)
                .contentType("image/png").originalFileName("fictitious.png").build());
        var board = app.getBean(WhiteboardSessionRepository.class).saveAndFlush(WhiteboardSession.builder()
                .name("Fictitious board").teacher(tp).grade("3").section("A")
                .status(WhiteboardSessionStatus.CLOSED).finalSnapshotData(bytes).finalSnapshotSize(3L)
                .finalSnapshotContentType("image/png").finalSnapshotFileName("fictitious.png").build());
        var sp = app.getBean(StudentProfileRepository.class).findByUser_Id(student.getId()).orElseThrow();
        app.getBean(WhiteboardParticipantRepository.class).saveAndFlush(WhiteboardParticipant.builder().session(board).student(sp).build());
        String download = "/api/concepts/" + concept.getId() + "/materials/" + material.getId() + "/download";
        for (UserAccount user : List.of(admin, teacher, student)) {
            String token = login(user);
            String prefix = switch (user.getRole()) { case ADMINISTRADOR -> "admin"; case DOCENTE -> "teacher"; case ESTUDIANTE -> "student"; };
            for (String path : List.of("/api/auth/me", "/api/chemistry/catalog/metals", "/api/concepts/" + prefix,
                    "/api/evaluations/" + prefix, "/api/whiteboards/" + prefix + (prefix.equals("student") ? "/active" : ""), download)) {
                assertStatus("GET", path, token, null, 200);
            }
            assertStatus("POST", "/api/usage-metrics/events", token,
                    "{\"module\":\"DASHBOARD\",\"eventType\":\"MODULE_ACCESS\"}", 201);
            assertStatus("GET", "/api/admin/users", token, null, user.getRole() == Role.ADMINISTRADOR ? 200 : 403);
            if (user.getRole() != Role.ADMINISTRADOR) assertStatus("GET", "/api/whiteboards/" + prefix + "/" + board.getId() + "/snapshot", token, null, 200);
        }
        String outsider = login(account(Role.DOCENTE, false));
        assertThat(request("GET", download, outsider, null).statusCode()).isIn(400, 403);
        assertThat(request("GET", "/api/whiteboards/teacher/" + board.getId() + "/snapshot", outsider, null).statusCode()).isIn(400, 403);
    }

    @Test void logoutOnlyCurrentGlobalLogoutBothAndPasswordChangeReplacesBothForAllRoles() throws Exception {
        for (Role role : Role.values()) {
            UserAccount user = account(role, true);
            String a = login(user), b = login(user);
            assertStatus("POST", "/api/auth/logout", a, "{\"userId\":999,\"sessionId\":\"ignored\"}", 204);
            assertStatus("GET", "/api/auth/me", a, null, 401);
            assertStatus("GET", "/api/auth/me", b, null, 200);
            a = login(user);
            assertStatus("POST", "/api/auth/logout-all", b, "{}", 204);
            assertStatus("GET", "/api/auth/me", a, null, 401);
            assertStatus("GET", "/api/auth/me", b, null, 401);
            a = login(user); b = login(user);
            var changed = request("PATCH", "/api/auth/change-temporary-password", a,
                    "{\"currentPassword\":\"" + PASSWORD + "\",\"newPassword\":\"NewFictitious123\",\"confirmPassword\":\"NewFictitious123\"}");
            assertThat(changed.statusCode()).isEqualTo(200);
            String replacement = body(changed).get("token").asText();
            assertThat(replacement).isNotEqualTo(a).isNotEqualTo(b);
            assertStatus("GET", "/api/auth/me", a, null, 401);
            assertStatus("GET", "/api/auth/me", b, null, 401);
            assertStatus("GET", "/api/chemistry/catalog/metals", replacement, null, 200);
        }
    }

    @ParameterizedTest(name = "incorrect password preserves {0}, temporary={1}; correct retry replaces sessions")
    @CsvSource({"ADMINISTRADOR,false", "ADMINISTRADOR,true", "DOCENTE,false", "DOCENTE,true",
            "ESTUDIANTE,false", "ESTUDIANTE,true"})
    void incorrectCurrentPasswordPreservesStateAndSessionsThenAllowsRetry(Role role, boolean temporary) throws Exception {
        UserAccount user = account(role, temporary);
        String a = login(user), b = login(user);
        var jdbc = app.getBean(JdbcTemplate.class);
        var beforeUser = jdbc.queryForMap("SELECT * FROM user_accounts WHERE id = ?", user.getId());
        var beforeSessions = jdbc.queryForList("SELECT * FROM account_sessions WHERE user_id = ? ORDER BY id", user.getId());
        assertThat(beforeSessions).hasSize(2);

        var rejected = request("PATCH", "/api/auth/change-temporary-password", a, passwordChangeBody("WrongFictitious123"));
        assertThat(rejected.statusCode()).isEqualTo(400);
        assertThat(body(rejected).path("code").asText()).isEqualTo("CURRENT_PASSWORD_INVALID");
        assertThat(body(rejected).path("message").asText()).isEqualTo("La contraseña actual es incorrecta.");
        // Compare the entire persisted row, without exposing its password hash in a failed assertion.
        assertThat(jdbc.queryForMap("SELECT * FROM user_accounts WHERE id = ?", user.getId()).equals(beforeUser))
                .as("Rejected change preserves password, temporary flag, credential version and account timestamps").isTrue();
        assertThat(jdbc.queryForList("SELECT * FROM account_sessions WHERE user_id = ? ORDER BY id", user.getId()))
                .as("Rejected change neither creates nor mutates sessions").isEqualTo(beforeSessions);
        assertStatus("GET", "/api/auth/me", a, null, 200);
        assertStatus("GET", "/api/auth/me", b, null, 200);

        var changed = request("PATCH", "/api/auth/change-temporary-password", a, passwordChangeBody(PASSWORD));
        assertThat(changed.statusCode()).isEqualTo(200);
        String replacement = body(changed).path("token").asText();
        assertThat(replacement).isNotBlank().isNotEqualTo(a).isNotEqualTo(b);
        var after = users().findById(user.getId()).orElseThrow();
        assertThat(app.getBean(PasswordEncoder.class).matches("NewFictitious123", after.getPassword())).isTrue();
        assertThat(after.getTemporaryPassword()).isFalse();
        assertThat(after.getCredentialsVersion()).isGreaterThan(((Number) beforeUser.get("credentials_version")).longValue());
        assertThat(jdbc.queryForList("SELECT * FROM account_sessions WHERE user_id = ?", user.getId())).hasSize(3);
        assertStatus("GET", "/api/auth/me", a, null, 401);
        assertStatus("GET", "/api/auth/me", b, null, 401);
        assertStatus("GET", "/api/chemistry/catalog/metals", replacement, null, 200);

        // A real revocation still wins over a form error on this same endpoint.
        assertStatus("POST", "/api/auth/logout", replacement, "{}", 204);
        assertStatus("PATCH", "/api/auth/change-temporary-password", replacement, passwordChangeBody("WrongFictitious123"), 401);
    }

    private String passwordChangeBody(String currentPassword) {
        return "{\"currentPassword\":\"" + currentPassword + "\",\"newPassword\":\"NewFictitious123\",\"confirmPassword\":\"NewFictitious123\"}";
    }

    @Test void currentAndLegacyResetDeactivationAndReactivationRevokeFutureTokens() throws Exception {
        String admin = login(account(Role.ADMINISTRADOR, false));
        UserAccount teacher = account(Role.DOCENTE, false);
        UserAccount student = account(Role.ESTUDIANTE, false);
        TeacherProfile tp = app.getBean(TeacherProfileRepository.class).findByUser(teacher).orElseThrow();
        var sp = app.getBean(StudentProfileRepository.class).findByUser_Id(student.getId()).orElseThrow();
        sp.setTeacher(tp); app.getBean(StudentProfileRepository.class).saveAndFlush(sp);
        String teacherToken = login(teacher);
        record Mutation(String actor, String path, String payload, UserAccount target) {}
        for (Mutation change : List.of(
                new Mutation(admin, "/api/admin/users/" + teacher.getId() + "/password/reset", "{}", teacher),
                new Mutation(admin, "/api/users/teachers/" + teacher.getId() + "/reset-password", "{\"newTemporaryPassword\":\"ResetFictitious123\",\"confirmTemporaryPassword\":\"ResetFictitious123\"}", teacher),
                new Mutation(teacherToken, "/api/users/teachers/" + teacher.getId() + "/students/" + sp.getId() + "/reset-password", "{\"newTemporaryPassword\":\"ResetFictitious123\",\"confirmTemporaryPassword\":\"ResetFictitious123\"}", student),
                new Mutation(admin, "/api/admin/users/" + student.getId() + "/deactivate", "{}", student),
                new Mutation(admin, "/api/users/" + student.getId() + "/deactivate", "{}", student),
                new Mutation(admin, "/api/users/teachers/" + teacher.getId() + "/deactivate", "{}", teacher),
                new Mutation(teacherToken, "/api/users/teachers/" + teacher.getId() + "/students/" + sp.getId() + "/deactivate", "{}", student))) {
            restore(teacher); restore(student);
            String actor = change.actor().equals(admin) ? admin : login(teacher);
            String old = login(change.target());
            assertThat(app.getBean(JwtService.class).parseClaims(old).getExpiration()).isAfter(new Date());
            assertStatus("PATCH", change.path(), actor, change.payload(), 200);
            assertStatus("GET", "/api/auth/me", old, null, 401);
            assertStatus("PATCH", "/api/admin/users/" + change.target().getId() + "/activate", admin, "{}", 200);
            assertStatus("GET", "/api/auth/me", old, null, 401);
        }
        restore(student);
        String old = login(student);
        mutate(student, user -> user.setRole(Role.ADMINISTRADOR));
        assertStatus("GET", "/api/auth/me", old, null, 401);
    }

    @Test void editingAccessScopeRevokesSessionsButCosmeticEditsPreserveThem() throws Exception {
        String admin = login(account(Role.ADMINISTRADOR, false));
        UserAccount student = account(Role.ESTUDIANTE, false);
        String old = login(student);
        String endpoint = "/api/admin/users/" + student.getId();
        assertStatus("PATCH", endpoint, admin,
                "{\"names\":\"Renamed\",\"lastNames\":\"Fixture\",\"grade\":\"3\",\"section\":\"A\"}", 200);
        assertStatus("GET", "/api/auth/me", old, null, 200);
        assertStatus("PATCH", endpoint, admin,
                "{\"names\":\"Renamed\",\"lastNames\":\"Fixture\",\"grade\":\"4\",\"section\":\"B\"}", 200);
        assertStatus("GET", "/api/auth/me", old, null, 401);
        var sp = app.getBean(StudentProfileRepository.class).findByUser_Id(student.getId()).orElseThrow();
        UserAccount teacher = users().findById(sp.getTeacher().getUser().getId()).orElseThrow();
        old = login(student);
        assertStatus("PUT", "/api/users/teachers/" + teacher.getId() + "/students/" + sp.getId(), login(teacher),
                "{\"names\":\"Renamed\",\"lastNames\":\"Fixture\",\"grade\":\"3\",\"section\":\"A\",\"active\":true}", 200);
        assertStatus("GET", "/api/auth/me", old, null, 401);
    }

    @Test void signatureExpirationLegacyClaimsAndConnectUseCentralValidation() throws Exception {
        UserAccount user = account(Role.DOCENTE, false);
        String valid = login(user);
        connect(valid);
        var claims = app.getBean(JwtService.class).parseClaims(valid);
        String legacy = Jwts.builder().subject(user.getUsername()).expiration(new Date(System.currentTimeMillis() + 60000))
                .signWith(Keys.hmacShaKeyFor(key)).compact();
        String expired = Jwts.builder().claims(claims).expiration(new Date(0)).signWith(Keys.hmacShaKeyFor(key)).compact();
        int signatureStart = valid.lastIndexOf('.') + 1;
        String altered = valid.substring(0, signatureStart)
                + (valid.charAt(signatureStart) == 'A' ? "B" : "A") + valid.substring(signatureStart + 1);
        for (String token : List.of(legacy, expired, altered)) {
            assertStatus("GET", "/api/auth/me", token, null, 401);
            assertStatus("PATCH", "/api/auth/change-temporary-password", token, passwordChangeBody("WrongFictitious123"), 401);
            assertThatThrownBy(() -> connect(token)).isInstanceOf(org.springframework.security.core.AuthenticationException.class);
        }
        String temporary = login(account(Role.ESTUDIANTE, true));
        assertThatThrownBy(() -> connect(temporary)).isInstanceOf(org.springframework.security.access.AccessDeniedException.class);
        assertStatus("POST", "/api/auth/logout", valid, "{}", 204);
        String revoked = valid;
        assertThatThrownBy(() -> connect(revoked)).isInstanceOf(org.springframework.security.core.AuthenticationException.class);
        valid = login(user);
        mutate(user, u -> u.setActive(false));
        String inactive = valid;
        assertStatus("PATCH", "/api/auth/change-temporary-password", inactive, passwordChangeBody("WrongFictitious123"), 401);
        assertThatThrownBy(() -> connect(inactive)).isInstanceOf(org.springframework.security.core.AuthenticationException.class);
    }

    @Test void revocationSurvivesRestartAndIsSharedByAnotherInstance() throws Exception {
        UserAccount user = account(Role.ADMINISTRADOR, false);
        String revoked = login(user), live = login(user);
        assertStatus("POST", "/api/auth/logout", revoked, "{}", 204);
        var first = app;
        try {
            startApp(); // same DB and key, independent pool/context
            assertStatus("GET", "/api/auth/me", revoked, null, 401);
            assertStatus("GET", "/api/auth/me", live, null, 200);
        } finally { first.close(); }
        app.close(); startApp();
        assertStatus("GET", "/api/auth/me", revoked, null, 401);
        assertStatus("GET", "/api/auth/me", live, null, 200);
        assertThat(users().findByUsername("preservedfixture").orElseThrow().getPassword()).isEqualTo("fictitious-hash");
    }

    @Test void loginActuallyWaitsForResetOrDeactivationPostgresLockAndCannotUseOldCredentials() throws Exception {
        for (boolean deactivate : List.of(false, true)) {
            UserAccount user = account(Role.DOCENTE, false);
            var pool = Executors.newFixedThreadPool(2);
            var locked = new CountDownLatch(1);
            var release = new CountDownLatch(1);
            try {
                var writer = pool.submit(() -> tx().executeWithoutResult(status -> {
                    var managed = users().findById(user.getId()).orElseThrow();
                    sessions().lock(managed);
                    locked.countDown();
                    try { if (!release.await(15, TimeUnit.SECONDS)) throw new IllegalStateException("test timeout"); }
                    catch (InterruptedException e) { throw new RuntimeException(e); }
                    if (deactivate) app.getBean(UserManagementService.class).deactivateTeacher(user.getId());
                    else app.getBean(UserManagementService.class).resetTeacherPassword(user.getId(),
                            new com.morales.chemicallab.dto.ResetPasswordRequest("ResetFictitious123", "ResetFictitious123"));
                }));
                assertThat(locked.await(10, TimeUnit.SECONDS)).isTrue();
                var login = pool.submit(() -> request("POST", "/api/auth/login", null, loginBody(user, PASSWORD)));
                // Observe a real waiting PostgreSQL backend, not just a thread start/barrier.
                boolean blocked = false;
                long deadline = System.nanoTime() + TimeUnit.SECONDS.toNanos(10);
                while (System.nanoTime() < deadline && !blocked) {
                    try (var statement = control.createStatement(); var rows = statement.executeQuery(
                            "select count(*) from pg_stat_activity where datname=current_database() and wait_event_type='Lock' "
                                    + "and query like '%user_accounts%'")) {
                        rows.next(); blocked = rows.getInt(1) > 0;
                    }
                    if (!blocked) Thread.sleep(30);
                }
                assertThat(blocked).as("login blocked on real account row lock").isTrue();
                assertThat(login.isDone()).isFalse();
                release.countDown(); writer.get(15, TimeUnit.SECONDS);
                assertThat(login.get(15, TimeUnit.SECONDS).statusCode()).isEqualTo(401);
                assertThat(app.getBean(AccountSessionRepository.class).findAll().stream()
                        .filter(s -> s.getUser().getId().equals(user.getId())).count()).isZero();
            } finally { release.countDown(); pool.shutdownNow(); }
        }
    }

    @Test void loginCommittingBeforeResetStillProducesOnlyARevokedOldSession() throws Exception {
        UserAccount user = account(Role.DOCENTE, false);
        var pool = Executors.newFixedThreadPool(2);
        var issued = new CountDownLatch(1);
        var release = new CountDownLatch(1);
        try {
            var login = pool.submit(() -> tx().execute(status -> {
                String token = app.getBean(AuthService.class).login(new LoginRequest(user.getUsername(), PASSWORD)).token();
                issued.countDown();
                try { if (!release.await(15, TimeUnit.SECONDS)) throw new IllegalStateException("test timeout"); }
                catch (InterruptedException e) { throw new RuntimeException(e); }
                return token;
            }));
            assertThat(issued.await(10, TimeUnit.SECONDS)).isTrue();
            var reset = pool.submit(() -> app.getBean(UserManagementService.class).resetTeacherPassword(user.getId(),
                    new com.morales.chemicallab.dto.ResetPasswordRequest("ResetFictitious123", "ResetFictitious123")));
            boolean blocked = false;
            long deadline = System.nanoTime() + TimeUnit.SECONDS.toNanos(10);
            while (!blocked && System.nanoTime() < deadline) {
                try (var statement = control.createStatement(); var rows = statement.executeQuery(
                        "select count(*) from pg_stat_activity where datname=current_database() and wait_event_type='Lock' and query like '%user_accounts%'")) {
                    rows.next(); blocked = rows.getInt(1) > 0;
                }
                if (!blocked) Thread.sleep(30);
            }
            assertThat(blocked).as("reset waits for login account lock").isTrue();
            release.countDown(); String old = login.get(15, TimeUnit.SECONDS); reset.get(15, TimeUnit.SECONDS);
            assertStatus("GET", "/api/auth/me", old, null, 401);
            assertStatus("POST", "/api/auth/login", null, loginBody(user, PASSWORD), 401);
            assertStatus("POST", "/api/auth/login", null, loginBody(user, "ResetFictitious123"), 200);
        } finally { release.countDown(); pool.shutdownNow(); }
    }

    @Test void rollbackPreservesCredentialsAndOldSessionAndDiscardsReplacement() throws Exception {
        UserAccount user = account(Role.ADMINISTRADOR, false);
        String old = login(user);
        long before = app.getBean(AccountSessionRepository.class).count();
        assertThatThrownBy(() -> tx().executeWithoutResult(status -> {
            var managed = users().findById(user.getId()).orElseThrow();
            sessions().lock(managed);
            managed.setPassword(app.getBean(PasswordEncoder.class).encode("RolledBack123"));
            sessions().issue(managed);
            throw new IllegalStateException("Force rollback of both credential and session");
        })).isInstanceOf(IllegalStateException.class);
        assertThat(app.getBean(AccountSessionRepository.class).count()).isEqualTo(before);
        assertStatus("GET", "/api/auth/me", old, null, 200);
        assertStatus("POST", "/api/auth/login", null, loginBody(user, PASSWORD), 200);
    }

    @Test void legacyStudentEditDeactivationAndBothActivationRoutesNeverResurrectTokens() throws Exception {
        UserAccount student = account(Role.ESTUDIANTE, false);
        var sp = app.getBean(StudentProfileRepository.class).findByUser_Id(student.getId()).orElseThrow();
        UserAccount teacher = users().findById(sp.getTeacher().getUser().getId()).orElseThrow();
        String admin = login(account(Role.ADMINISTRADOR, false));
        String old = login(student);
        String teacherToken = login(teacher);
        assertStatus("PUT", "/api/users/teachers/" + teacher.getId() + "/students/" + sp.getId(), teacherToken,
                "{\"names\":\"Fictitious\",\"lastNames\":\"Student\",\"grade\":\"3\",\"section\":\"A\",\"active\":false}", 200);
        assertStatus("GET", "/api/auth/me", old, null, 401);
        assertStatus("PATCH", "/api/users/" + student.getId() + "/activate", admin, "{}", 200);
        assertStatus("GET", "/api/auth/me", old, null, 401);
        assertStatus("GET", "/api/auth/me", login(student), null, 200);
    }

    @Test void expiredSessionsAreDeletedWithoutDeletingUsers() {
        var user = account(Role.ADMINISTRADOR, false);
        var repository = app.getBean(AccountSessionRepository.class);
        UUID id = UUID.randomUUID();
        repository.saveAndFlush(AccountSession.builder().id(id).user(user).createdAt(Instant.EPOCH)
                .expiresAt(Instant.EPOCH.plusSeconds(1)).build());
        app.getBean(SessionCleanup.class).deleteExpired();
        assertThat(repository.findById(id)).isEmpty();
        assertThat(users().findById(user.getId())).isPresent();
    }

    private void connect(String token) {
        var headers = StompHeaderAccessor.create(StompCommand.CONNECT);
        String id = UUID.randomUUID().toString();
        headers.setSessionId(id);
        var socket = org.mockito.Mockito.mock(org.springframework.web.socket.WebSocketSession.class);
        org.mockito.Mockito.when(socket.getId()).thenReturn(id);
        var closed = new java.util.concurrent.atomic.AtomicReference<org.springframework.web.socket.CloseStatus>();
        try { org.mockito.Mockito.doAnswer(inv -> { closed.set(inv.getArgument(0)); return null; }).when(socket).close(org.mockito.ArgumentMatchers.any()); }
        catch (Exception ex) { throw new AssertionError(ex); }
        var connections = app.getBean(WhiteboardConnections.class);
        try { connections.decorate(new org.springframework.web.socket.handler.TextWebSocketHandler()).afterConnectionEstablished(socket); }
        catch (Exception ex) { throw new AssertionError(ex); }
        headers.setNativeHeader("Authorization", "Bearer " + token);
        headers.setLeaveMutable(true);
        var message = MessageBuilder.createMessage(new byte[0], headers.getMessageHeaders());
        try {
            var result = app.getBean(WhiteboardStompAuthChannelInterceptor.class).preSend(message, new ExecutorSubscribableChannel());
            if (result == null) {
                if (closed.get().getCode() == 4001) throw new org.springframework.security.authentication.BadCredentialsException("SESSION_INVALID");
                throw new org.springframework.security.access.AccessDeniedException("CONNECT_REJECTED");
            }
            assertThat(headers.getUser()).isNotNull();
        } finally { connections.remove(id); }
    }
    private void restore(UserAccount user) {
        mutate(user, u -> { u.setActive(true); u.setTemporaryPassword(false); u.setPassword(app.getBean(PasswordEncoder.class).encode(PASSWORD)); });
    }
    private void mutate(UserAccount user, Consumer<UserAccount> mutation) {
        tx().executeWithoutResult(status -> {
            var managed = users().findById(user.getId()).orElseThrow(); sessions().lock(managed); mutation.accept(managed);
        });
    }
    private UserAccount account(Role role, boolean temporary) {
        UserAccount account = users().saveAndFlush(UserAccount.builder().username("fixture" + sequence.incrementAndGet())
                .email("fixture" + sequence.get() + "@example.invalid")
                .password(app.getBean(PasswordEncoder.class).encode(PASSWORD)).role(role).temporaryPassword(temporary).build());
        if (role == Role.DOCENTE) app.getBean(TeacherProfileRepository.class).saveAndFlush(TeacherProfile.builder()
                .user(account).names("Fictitious").lastNames("Teacher").build());
        if (role == Role.ESTUDIANTE) {
            UserAccount teacher = account(Role.DOCENTE, false);
            var tp = app.getBean(TeacherProfileRepository.class).findByUser(teacher).orElseThrow();
            app.getBean(StudentProfileRepository.class).saveAndFlush(StudentProfile.builder().user(account).teacher(tp)
                    .studentCode(account.getUsername()).names("Fictitious").lastNames("Student").grade("3").section("A").build());
        }
        return account;
    }
    private String login(UserAccount user) throws Exception {
        var response = request("POST", "/api/auth/login", null, loginBody(user, PASSWORD));
        assertThat(response.statusCode()).isEqualTo(200);
        return body(response).get("token").asText();
    }
    private String loginBody(UserAccount user, String password) { return "{\"usernameOrEmail\":\"" + user.getUsername() + "\",\"password\":\"" + password + "\"}"; }
    private HttpResponse<String> request(String method, String path, String token, String payload) throws Exception {
        var builder = HttpRequest.newBuilder(URI.create(origin + path)).timeout(Duration.ofSeconds(20))
                .header("Content-Type", "application/json");
        if (token != null) builder.header("Authorization", "Bearer " + token);
        return http.send(builder.method(method, payload == null ? HttpRequest.BodyPublishers.noBody() : HttpRequest.BodyPublishers.ofString(payload)).build(), HttpResponse.BodyHandlers.ofString());
    }
    private void assertStatus(String method, String path, String token, String payload, int status) throws Exception {
        var response = request(method, path, token, payload);
        assertThat(response.statusCode()).as(method + " " + path + " => " + response.body()).isEqualTo(status);
    }
    private JsonNode body(HttpResponse<String> response) throws Exception { return json.readTree(response.body()); }
    private TransactionTemplate tx() { return new TransactionTemplate(app.getBean(PlatformTransactionManager.class)); }
    private UserAccountRepository users() { return app.getBean(UserAccountRepository.class); }
    private AccountSessionService sessions() { return app.getBean(AccountSessionService.class); }
    private String setting(String name) { return Objects.requireNonNull(System.getProperty(name), "Required disposable DB setting: " + name); }
}
